### fin profile config
fin_profile_path: ""

### server paths
local_server_path: ""
prod_server_path: ""
systems_server_path: ""
dropbox_path: ""
backup_server_path: ""

### template paths
project_dir_template: ""

### ocio default
ocio_default: ""

### master reference img and vid paths
ref_img_path: ""
ref_vid_path: ""
ref_tut_path: ""

### application paths
veracrypt_app: ""
vlc_app: ""
firefox_app: ""

### image viewers
djview_app: ""
djv_bin_path: ""
bview_app: ""
batch_bview_app: ""

# RV
rv_app: ""
rvpkg_app: ""

# Nuke
nuke_app: ""
nukex_app: ""
nukestudio_app: ""

# adobe
photoshop_app: ""
aftereffects_app: ""

# maya
maya_app: ""
maya_location: ""
maya_bin_path: ""

# meshlab    
meshlab_app: ""
meshlabserver_app: ""

# komodo
komodo_app: ""

# gimp
gimp_app: ""

# redcine-x and redline
redcine_app: ""
redline_app: ""